exclude_patterns:
- ".github/"
- ".nyc_output/"
- ".vscode/"
- ".yarn/"
- "coverage/"
- "dist/"
- ".editorconfig"
- ".elintignore"
- ".gitignore"
- ".nvmrc"
- ".pnp.js"
- ".prettierignore"
- "rollup.config.*"
- "**/*.json"
- "**/*.jsonc"
- "**/*.md"
- "**/*.browser.ts"
- "**/*.spec.ts"
- "**/*.yml"
