packageExtensions:
  "@antfu/eslint-config-ts@*":
    dependencies:
      typescript: "*"
  "@docsearch/react@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  ts-node@*:
    dependencies:
      typescript: "*"
  vitepress@*:
    dependencies:
      "@vue/runtime-dom": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
