name: Publish to GitHub Packages
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: tag
      uses: WyriHaximus/github-action-get-previous-tag@master
    - uses: reedyuk/npm-version@master
      with:
        version: ${{ steps.tag.outputs.tag }}
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: yarn install
    - run: yarn build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
