name: Test
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  mocha:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn test
