name: Test & publish coverage
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  test-and-publish-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3.0.0
      with:
        node-version: '16'
    - run: yarn install
    - run: yarn test
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
